const fs=require('fs');const path=require('path');const {chromium}=require('playwright');
const root=__dirname;const routes=JSON.parse(fs.readFileSync(path.join(root,'site/route-manifest.json')));const base=process.env.GA_TEST_URL||'http://127.0.0.1:8775';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage();let jsErrors=[];page.on('pageerror',e=>jsErrors.push(String(e)));let checks=[];fs.mkdirSync(path.join(root,'validacion/capturas'),{recursive:true});
for(const width of (process.env.GA_RECHECK_ACCESSIBILITY ? [] : [320,390,768,1024,1440])){await page.setViewportSize({width,height:900});for(const r of routes){let response=await page.goto(base+r.path);await page.evaluate(()=>document.fonts.ready);let result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelectorAll('h1').length,main:!!document.querySelector('main'),formFields:document.querySelectorAll('[data-consultation] input,[data-consultation] select').length,enabled:[...document.querySelectorAll('[data-consultation] button[type=submit]')].every(x=>!x.disabled)}));checks.push({path:r.path,width,status:response.status(),...result});}console.log('Completed',width,routes.length,'pages');}
const samples=['/','/servicios/','/servicios/auditoria-monterrey/','/nosotros/','/equipo/','/contacto/','/perspectivas/','/perspectivas/preparar-auditoria-financiera/','/lp/contabilidad/'];let a11y=[];const axePath=require.resolve('axe-core/axe.min.js',{paths:[process.env.GA_QA_MODULES||path.join(root,'node_modules'),'/tmp/ga-qa/node_modules']});
for(const width of [390,1440]){await page.setViewportSize({width,height:1000});for(const r of (width===390 ? routes.map(x=>x.path) : [...samples,'/en/services/accounting-monterrey/','/en/contact/','/aviso-de-privacidad/'])){await page.goto(base+r);await page.evaluate(()=>document.fonts.ready);await page.addScriptTag({path:axePath});const result=await page.evaluate(async()=>{const x=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','best-practice']}});return x.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));});a11y.push({path:r,width,violations:result});if(samples.includes(r))await page.screenshot({path:path.join(root,'validacion/capturas',r.replaceAll('/','_')+'-'+width+'.png'),fullPage:true});}console.log('Accessibility completed',width);}
await page.setViewportSize({width:390,height:844});await page.goto(base+'/servicios/auditoria-monterrey/');await page.locator('.mobile-menu summary').click();const menuOpened=await page.locator('.mobile-menu').evaluate(e=>e.open);await page.keyboard.press('Escape');const menuClosed=await page.locator('.mobile-menu').evaluate(e=>!e.open);await page.locator('.faqs summary').first().click();const faqOpened=await page.locator('.faqs details').first().evaluate(e=>e.open);await page.locator('[name=name]').fill('Responsive QA');await page.locator('[name=company]').fill('Layout test');await page.locator('[name=phone]').fill('123');await page.locator('form button[type=submit]').click();const invalidPhone=await page.locator('[name=phone]').evaluate(e=>!e.checkValidity());const noAutomaticMap=await page.locator('iframe').count()===0;
if(process.env.GA_RECHECK_ACCESSIBILITY)checks=JSON.parse(fs.readFileSync(path.join(root,'validacion/paginas-completas-browser.json'))).checks;
const errors=checks.filter(x=>x.status!==200||x.overflow||x.h1!==1||!x.main||!x.enabled||(x.formFields!==0&&x.formFields!==4));const violations=a11y.filter(x=>x.violations.length);const report={views:checks.length,checks,errors,jsErrors,a11y,flows:{menuOpened,menuClosed,faqOpened,invalidPhone,noAutomaticMap}};fs.writeFileSync(path.join(root,'validacion/paginas-completas-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({views:checks.length,errors,jsErrors,accessibilityViolations:violations,flows:report.flows},null,2));await browser.close();if(errors.length||jsErrors.length||violations.length||Object.values(report.flows).includes(false))process.exit(1);})().catch(e=>{console.error(e);process.exit(1)});
